/sub1/car_model:
  ros__parameters:
    init_pose: [-2.21, -2.39, 0.0]

/sub2/car_model:
  ros__parameters:
    init_pose: [-1.81, -1.49, 0.0]

/sub3/car_model:
  ros__parameters:
    init_pose: [-0.19, -2.39, 0.0]

/sub4/car_model:
  ros__parameters:
    init_pose: [-1.31, -1.49, 0.0]

/sub5/car_model:
  ros__parameters:
    init_pose: [2.69, 0.00, 0.0]

/sub6/car_model:
  ros__parameters:
    init_pose: [1.95, 0.00, 0.0]