setups:
  real_robots:
    rear_end_robot_names: # cable_plan_executor, cable_action_planner
      - sub2
      - sub4
      - sub1
    front_end_robot_names: # cable_plan_executor, cable_action_planner
      - sub5
      - sub8
      - sub3
  simulation:
    rear_end_robot_names: # cable_plan_executor, cable_action_planner
      - sub1
      - sub3
      - sub5
    front_end_robot_names: # cable_plan_executor, cable_action_planner
      - sub2
      - sub4
      - sub6
