static_tf_node:
  ros__parameters:
    x: -3.6
    y: -2.4
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    frame_id: "world"
    child_frame_id: "map"

cable_plan_executor:
  ros__parameters:
    plan_filepath: "resources/data/s1_m3.json"
    skip_interlaces: False
    action_server_timeout: 5.0

cable_action_planner:
  ros__parameters:
    n_threads: 4
    server_timeout: 5.0
    tf_timeout: 10.0
    communication_timeout: 5.0
    path_planner_timeout: 5.0
    progress_last_wp_fallback_scale_default: 2.0
    progress_last_wp_fallback_scale_step: 0.5
    progress_last_wp_fallback_scale_max: 0.5
    progress_last_wp_fallback_attempts_max: 5
    progress_replan_attempts_max : 100
    interlace_circle_fallback_default: 0.5
    interlace_circle_fallback_step: 0.1
    interlace_circle_fallback_max_attempts: 5
    interlace_move_away_fallback_scale_default: 4.0
    interlace_move_away_fallback_scale_step: 1.0
    interlace_move_away_fallback_attempts_max: 6

path_planner:
  ros__parameters:
    n_threads: 4
    map_yaml_filepath: "resources/maps/rr_s1.yaml"
    tf_timeout: 10.0
    inter_robot_collision_check_factor: 2.6
    image_coords_scale: 100.0
    robot_push_scale_default: 1.0
    robot_push_scale_step: 0.1
    robot_push_scale_max_attempts: 20
    boundary_push_scale_default: 0.0
    boundary_push_scale_step: 0.1
    boundary_push_scale_max_attempts: 10
    obstacle_push_scale_default: 1.0
    obstacle_push_scale_step: 0.5
    obstacle_push_scale_max_attempts: 3

map_server:
  ros__parameters:
    yaml_filename: "resources/maps/rr_s1.yaml"
    frame_id: "map"

/**:
  ros__parameters:
    target_frame: "map" # feedback_lin_ctrl, robot_visualizer, cable_action_planner, path_planner
    robot_radius: 0.15 # robot_visualizer, cable_action_planner, path_planner
    robot_height: 0.05 # robot_visualizer
    robot_color: [0.1, 0.4, 1.0, 1.0] # robot_visualizer
    selected_robot_color: [1.0, 0.4, 0.1, 1.0] # robot_visualizer
    control_frequency: 20 # feedback_lin_ctrl
    d_epsilon: 0.1 # feedback_lin_ctrl
    angle_epsilon: 0.6 # feedback_lin_ctrl
    lookahead_distance: 0.3 # feedback_lin_ctrl
    max_linear_vel: 0.5 # feedback_lin_ctrl
    max_rotational_vel: 0.6 # feedback_lin_ctrl
    n_spline_samples: 100 # feedback_lin_ctrl
    lookahead_search_ahead: 1.0 # feedback_lin_ctrl
    lookahead_search_behind: 0.2 # feedback_lin_ctrl
    collision_radius: 0.6 # feedback_lin_ctrl
    collision_break_factor: 0.76 # feedback_lin_ctrl
